//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApp.BLL.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/WCFDataService.Entities")]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreationDateField, value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INewsService")]
    public interface INewsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/GetArticles", ReplyAction="http://tempuri.org/INewsService/GetArticlesResponse")]
        NewsApp.BLL.ServiceReference1.GetArticlesResponse GetArticles(NewsApp.BLL.ServiceReference1.GetArticlesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/GetArticles", ReplyAction="http://tempuri.org/INewsService/GetArticlesResponse")]
        System.Threading.Tasks.Task<NewsApp.BLL.ServiceReference1.GetArticlesResponse> GetArticlesAsync(NewsApp.BLL.ServiceReference1.GetArticlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/GetArticle", ReplyAction="http://tempuri.org/INewsService/GetArticleResponse")]
        NewsApp.BLL.ServiceReference1.Article GetArticle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/GetArticle", ReplyAction="http://tempuri.org/INewsService/GetArticleResponse")]
        System.Threading.Tasks.Task<NewsApp.BLL.ServiceReference1.Article> GetArticleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/CreateArticle", ReplyAction="http://tempuri.org/INewsService/CreateArticleResponse")]
        NewsApp.BLL.ServiceReference1.Article CreateArticle(NewsApp.BLL.ServiceReference1.Article item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/CreateArticle", ReplyAction="http://tempuri.org/INewsService/CreateArticleResponse")]
        System.Threading.Tasks.Task<NewsApp.BLL.ServiceReference1.Article> CreateArticleAsync(NewsApp.BLL.ServiceReference1.Article item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/UpdateArticle", ReplyAction="http://tempuri.org/INewsService/UpdateArticleResponse")]
        NewsApp.BLL.ServiceReference1.Article UpdateArticle(NewsApp.BLL.ServiceReference1.Article item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/UpdateArticle", ReplyAction="http://tempuri.org/INewsService/UpdateArticleResponse")]
        System.Threading.Tasks.Task<NewsApp.BLL.ServiceReference1.Article> UpdateArticleAsync(NewsApp.BLL.ServiceReference1.Article item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/DeleteArticle", ReplyAction="http://tempuri.org/INewsService/DeleteArticleResponse")]
        int DeleteArticle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/DeleteArticle", ReplyAction="http://tempuri.org/INewsService/DeleteArticleResponse")]
        System.Threading.Tasks.Task<int> DeleteArticleAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArticles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetArticlesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int page;
        
        public GetArticlesRequest() {
        }
        
        public GetArticlesRequest(int page) {
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArticlesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetArticlesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NewsApp.BLL.ServiceReference1.Article[] GetArticlesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int numberOfItems;
        
        public GetArticlesResponse() {
        }
        
        public GetArticlesResponse(NewsApp.BLL.ServiceReference1.Article[] GetArticlesResult, int numberOfItems) {
            this.GetArticlesResult = GetArticlesResult;
            this.numberOfItems = numberOfItems;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsServiceChannel : NewsApp.BLL.ServiceReference1.INewsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsServiceClient : System.ServiceModel.ClientBase<NewsApp.BLL.ServiceReference1.INewsService>, NewsApp.BLL.ServiceReference1.INewsService {
        
        public NewsServiceClient() {
        }
        
        public NewsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewsApp.BLL.ServiceReference1.GetArticlesResponse NewsApp.BLL.ServiceReference1.INewsService.GetArticles(NewsApp.BLL.ServiceReference1.GetArticlesRequest request) {
            return base.Channel.GetArticles(request);
        }
        
        public NewsApp.BLL.ServiceReference1.Article[] GetArticles(int page, out int numberOfItems) {
            NewsApp.BLL.ServiceReference1.GetArticlesRequest inValue = new NewsApp.BLL.ServiceReference1.GetArticlesRequest();
            inValue.page = page;
            NewsApp.BLL.ServiceReference1.GetArticlesResponse retVal = ((NewsApp.BLL.ServiceReference1.INewsService)(this)).GetArticles(inValue);
            numberOfItems = retVal.numberOfItems;
            return retVal.GetArticlesResult;
        }
        
        public System.Threading.Tasks.Task<NewsApp.BLL.ServiceReference1.GetArticlesResponse> GetArticlesAsync(NewsApp.BLL.ServiceReference1.GetArticlesRequest request) {
            return base.Channel.GetArticlesAsync(request);
        }
        
        public NewsApp.BLL.ServiceReference1.Article GetArticle(int id) {
            return base.Channel.GetArticle(id);
        }
        
        public System.Threading.Tasks.Task<NewsApp.BLL.ServiceReference1.Article> GetArticleAsync(int id) {
            return base.Channel.GetArticleAsync(id);
        }
        
        public NewsApp.BLL.ServiceReference1.Article CreateArticle(NewsApp.BLL.ServiceReference1.Article item) {
            return base.Channel.CreateArticle(item);
        }
        
        public System.Threading.Tasks.Task<NewsApp.BLL.ServiceReference1.Article> CreateArticleAsync(NewsApp.BLL.ServiceReference1.Article item) {
            return base.Channel.CreateArticleAsync(item);
        }
        
        public NewsApp.BLL.ServiceReference1.Article UpdateArticle(NewsApp.BLL.ServiceReference1.Article item) {
            return base.Channel.UpdateArticle(item);
        }
        
        public System.Threading.Tasks.Task<NewsApp.BLL.ServiceReference1.Article> UpdateArticleAsync(NewsApp.BLL.ServiceReference1.Article item) {
            return base.Channel.UpdateArticleAsync(item);
        }
        
        public int DeleteArticle(int id) {
            return base.Channel.DeleteArticle(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteArticleAsync(int id) {
            return base.Channel.DeleteArticleAsync(id);
        }
    }
}
