USE SZemba_Practice;
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=
      'dbo' AND TABLE_NAME='News')
      BEGIN
        CREATE TABLE dbo.News(
			Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
			Title NVARCHAR(200) NOT NULL,
			ShortDescription NVARCHAR(50) NOT NULL,
			Content NVARCHAR(MAX) NOT NULL,
			ImageName NVARCHAR(MAX) NOT NULL,
			CreationDate DATETIME NOT NULL
		);
      END
GO